version: "3.9"

services:
    backend:
        image: unknown/backend
        build: ./backend
        restart: always
        environment:
            ACCOUNT_SID: ${ACCOUNT_SID}
            AUTH: ${AUTH}
            FROM_NUMBER: ${FROM_NUMBER}
        ports:
            - "5000:5000"

    frontend:
        image: unknown/frontend
        build:
            context: ./frontend
            args:
                REACT_APP_BACKEND_URL: ${BACKEND_URL}
        restart: always
        ports:
            - "3000:80"
        depends_on:
            - backend
